version: '3'

services:
  apache:
    container_name: ninjalinks
    image: ninjalinks-apache
    build: docker
    ports:
      - 8082:80
      - 9001:9001
    depends_on:
      - mysql
      - mailhog
    links:
      - mysql
    volumes:
      - ./public/ninjalinks:/app/public/ninjalinks
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./rector.php:/app/rector.php
      - ./phpstan.neon:/app/phpstan.neon
      - ./phpstan-baseline.neon:/app/phpstan-baseline.neon
      - ./phpstan:/app/phpstan
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/configs/config.php:/app/public/ninjalinks/config.php:ro
      - php-vendor:/app/vendor
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.222.1 remote_enable=1 remote_port=9002"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - internal

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ninjalinks
      MYSQL_USER: ninjalinks
      MYSQL_PASSWORD: password
    ports:
      - 13306:3306
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8011:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

volumes:
  php-vendor:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28
